### ISSUE TITLE
Bad results for pb model inference?

### ISSUE THREAD

**Issue by ymzlygw** [nolan-dev/GANInterface#18]
@nolan-dev 
Hi, firstly really thanks for your work.
I am finding a way to convert stylegan2.pkl model to .pb file. And I get succeed using your pkl_convert fuc, thanks!
The problem is that after I trying 2 model (ffhq-512-config-f.pkl and animeportraits-conf-f-512.pkl) and convert them to pb format, 
then inference using .pb model.
But ffhq is good but anime is worse. I don't know why, Could you please tell me why about this ? 

ffhq Result:
ffhq pkl model: https://drive.google.com/file/d/1Krc_m8Nj2PQXu9yBUnJ8-Na4mud_VCIj/view?usp=sharing
![good](https://user-images.githubusercontent.com/17065855/144588174-41202a5f-af10-454b-bbfa-6c257de20d3f.png)

anime Result: 
anime pkl model: https://drive.google.com/file/d/1exJwAJQT6BsdStyfuOkBTyZF4QeK5T61/view?usp=sharing
![bad_1](https://user-images.githubusercontent.com/17065855/144588188-f4837c27-b994-4300-be64-6d060553c6b2.png)

Part inference code:

    input_tensor = graph.get_tensor_by_name('Gs/dlatent_avg:0')
    output_tensor = graph.get_tensor_by_name('Gs/G_synthesis/output:0')

**Comment by nolan-dev** [comment]
Hi,
Unfortunately I haven't worked on this in a while and from what I remember the conversion was pretty brittle and hacky because it involved patching a specific commit of nvidia's stylegan2 implementation.  One cause could be that the animeportraits-conf-f-512.pkl was trained with a updated version of sylegan2 (beyond the commit 4874628c7dfffaae01f89558c476842b475f54d5 used in the conversion script), in which case fixing might be tricky.

Are you sure that the anime model is supposed to generate high quality images even without the 'truncation trick'?  The best quality images I was able to get required using that, which I implemented as the 'Quality' slider in the tool (if you use the included anime faces model with the quality slider set to the highest variation/lowest quality, the results aren't great either).  That requires generating a lot of images, and taking the average of their intermediate latent variables, setting that as the 'base' image, and interpolating from there.  If you use a converted model the quality slider will be set to 'lowest quality/highest variation' because it doesn't have the average intermediate latent variable to interpolate from.  The ffhq model is different in that it can generate decent images even with maximum variation.  If that's the problem it might only take a few lines of code to fix.

**Comment by ymzlygw** [comment]
@nolan-dev 
Thanks for your reply! Sry I don't know wether it support that or not . The trained anime model is finetuned from ffhq and can be inference well at https://github.com/justinpinkney/stylegan2 here. If any possilbe could please help see that  for a while?Thanks

**Comment by nolan-dev** [comment]
Hmm, that implementation might be sufficiently different from the original that it creates issues with the conversion process.  Unfortunately I don't have time to update it for new variations of stylegan2 right now.  Are you totally sure that the anime model should be producing better results without using the truncation trick? 
For example, the model I included originally often produced poor results kind of like the ones you demonstrated if the 'quality' slider was all the way to the right, but the images became higher quality when it was shifted:
![image](https://user-images.githubusercontent.com/566613/145531690-8ac6b944-514c-46ef-b14f-373374cfff36.png)
By default, with new models the quality slider doesn't work and it always produces the lowest-quality/highest variation images the model can create.  Making the quality slider work requires using the model to generate a bunch of latent variables and averaging them together, which probably easier than fixing the conversion script.

**Comment by nolan-dev** [comment]
*just realized you're just using the conversion tool and using a python notebook instead of the tool.  Are you trying to get the model to work with the tool, or do you just want to convert it from pkl to pb?  If you don't need to use the tool, then the conversion process should be quite a bit simpler, and less likely to break with new versions of stylegan2.

**Comment by ymzlygw** [comment]
> 
@nolan-dev 
Thanks for your reply. I have just used your script to convert the two pkl models to .pb files. Then I use the .pb model to do inference and get the above result. I didn't use the tool.

**Comment by nolan-dev** [comment]
It has been a while since I worked on this so I'm not totally sure if this is right, but I think using the script in this project adds unnecessary complexity if all you want to do is convert a pkl file to a pb file.  Most of the complexity of the script is due to the need to modify the model in the pkl file before saving it as a pb, in order to get it to work with the tool in this repository.

If you don't need to do that, you can probably just load the pkl and then save it as a pb directly without any modification step.  If I remember correctly, the way to generate the pb file was to call tf.save_model.simple_save (like here https://github.com/nolan-dev/GANInterface/blob/d70b7f7a99b606d90fd42c18d41b8761fd1b0b08/pkl_conversion/patch.diff#L481) and then run the freeze_graph tool on the output (like here https://github.com/nolan-dev/GANInterface/blob/d70b7f7a99b606d90fd42c18d41b8761fd1b0b08/pkl_conversion/download_and_patch.sh#L11).

**Comment by ymzlygw** [comment]
> 

Ok, really thanks for that! I will try it later.
