### ISSUE TITLE
Convert .pkl files from official implementation to .pb files that can be loaded by this tool

### ISSUE THREAD

**Issue by nolan-dev** [nolan-dev/GANInterface#3]
Loose plan: 
1. add ops like [this](https://github.com/nolan-dev/stylegan_reimplementation/blob/master/models.py#L414) to the official implementation
2. load a pkl file, save using a method like [this](https://github.com/nolan-dev/stylegan_reimplementation/blob/master/evaluation.py#L36)
3. rename and resize the following lists in the tool:
https://github.com/nolan-dev/GANInterface/blob/master/GanStudio/GanStudio/LatentManipulator.cs#L154
https://github.com/nolan-dev/GANInterface/blob/master/GanStudio/GanStudio/LatentManipulator.cs#L167

**Comment by nathanshipley** [comment]
Nvidia published a [link](https://drive.google.com/open?id=1MASQyN5m0voPcx7-9K0r5gObhvvPups7) to their models on Drive if you need a .PKL file to play with.

As I understand it, the networks and models are handled by their [dnnlib.tflib.network](https://github.com/NVlabs/stylegan/blob/master/dnnlib/tflib/network.py) script.  It gets opened back up with pickle.load as shown in one example [here](https://github.com/NVlabs/stylegan/blob/master/pretrained_example.py#L25).

Really appreciate you looking at this.

**Comment by net2cn** [comment]
Hi,
I have done some magnificent breakthroughs in converting the original .pkl model to the .pb one (which is simply a frozen model) in one of my personal experiments. The frozen model can be used in inference with TensorFlow.NET. Based on this, I have successfully converted the .pb model to .json model for TensorFlow.js and get it running in a browser. I suggest you investigate [this repo](https://github.com/moono/stylegan-reproduced) for more info (since I was inspired by this repo).

Here's the online demo of the tfjs implementation hosted on GitHub Pages by one of my friends: [this repo](https://github.com/Rand0mZharp/gan.js).

**Comment by nolan-dev** [comment]
Thanks for the pointers.  I have a way to convert but it's really hacky right now, so I might check out that repo if I can't find a quick way to clean it up.  Check out https://github.com/nolan-dev/GANInterface/issues/4#issuecomment-588662983 for more info.

**Comment by nolan-dev** [comment]
Added (a messy) way to convert from pkl to a format readable by the tool here: https://github.com/nolan-dev/GANInterface/tree/master/pkl_conversion
