### ISSUE TITLE
System.FormatException when launching or using some features

### ISSUE THREAD

**Issue by Tempetek** [nolan-dev/GANInterface#5]
Hello, I got an error when trying to launch the interface or using some of the features (for example, I can't import images):

> System.FormatException: Input string was not in a correct format.
>    at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
>    at System.Single.Parse(String s)
>    at System.Array.ConvertAll[TInput,TOutput](TInput[] array, Converter`2 converter)
>    at GanimeStudio.LatentManipulator.ReadAverageLatentFromCsv(String csvPath)
>    at GanimeStudio.GanimeStudio.Form1_Load(Object sender, EventArgs el)
>    at System.Windows.Forms.Form.OnLoad(EventArgs e)
>    at System.Windows.Forms.Form.OnCreateControl()
>    at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    at System.Windows.Forms.Control.CreateControl()
>    at System.Windows.Forms.Control.WmShowWindow(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.Form.WmShowWindow(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I have .NET framework 4.7 installed (and others versions as well, perhaps it's conflicting).

**Comment by nolan-dev** [comment]
Hi Tempetek, thanks for letting me know about the issue.
My best guess is that it's an issue with regional treatment of decimal formatting.  If you don't mind sharing, could you let me know what your region is set to so I can double check?  It should be in control panel -> clock and region -> region -> format.  For example, my default is English (United States) which works, but when I switch to English (Denmark) the results I get are wrong due to how decimal numbers are formatted.

In any case I'll update it to be region invariant.

**Comment by nolan-dev** [comment]
Hi, please try out the most recent compiled version: https://github.com/nolan-dev/GANInterface/releases/download/v0.2.0-alpha/GanStudio_x64_v2.zip and let me know if it still doesn't work.

**Comment by Tempetek** [comment]
This one seems to work. Thank you for the quick reply!

For the record, my region is set to France (the clock is Europe/Paris - UTC+01:00 with DST). I was using the release described in https://towardsdatascience.com/animating-ganime-with-stylegan-the-tool-c5a2c31379d. It linked to a drive where there were three versions - all of which gave me the same error.
