### ISSUE TITLE
Non frozen models?

### ISSUE THREAD

**Issue by flumf** [nolan-dev/GANInterface#9]
I was looking into porting this to something like pytorch, however in order to do so (efficiently) I would need the non frozen models (the checkpoints, meta, etc). I was wondering if you'd be willing to upload said data somewhere :)

Thanks

**Comment by nolan-dev** [comment]
Hi Flumf, I'd be happy to look into sharing non-frozen models, but as these models are a bit old and you may be able to get better results with more recent stylegan2 models.  I haven't trained any myself, but https://www.gwern.net/Faces has a pretty comprehensive outline of anime GAN models. https://github.com/nolan-dev/GANInterface/tree/master/pkl_conversion should hopefully still work to convert stylegan2 pkls to frozen graphs and you can change some lines around https://github.com/nolan-dev/GANInterface/blob/master/pkl_conversion/download_and_patch.sh#L11 to stop the graphs from getting frozen.

However, if you use other models you'd need to find new attribute/feature map vectors.  I hope my blogs on this tool have enough detail for how you could do that if you want to try.  If you're not interested in trying other models let me know and I'll try and find the non-frozen models.

**Comment by flumf** [comment]
Hey, thanks for the quick response!

I've actually tried out getting the models from gwern to work, but the overall quality of them is honestly lacking, which I found kind of surprising. I figured that stylegan2 would have better but the older models I tried out w/ ganstudio worked better. If it's not too much of a hassle for you to find the non frozen ones, that'd be great.

**Comment by nolan-dev** [comment]
Interesting that the quality would be worse, did you try the truncation trick with both (quality/variation bar in ganstudio)?  The only other reasons I can think of are variation in the dataset (I took a lot of steps to reduce variation in the training data), or some benefit from multitask learning because it generated both faces and torsos.  On that topic, the model I included in the GanStudio zip files has an extra operation included to crop off everything below the face (making the output 256x256 instead of 256x512), as due to the nature of the dataset a high percentage of the uncropped images are NSFW.  The unfrozen version I found doesn't include that, so only use it if you're ok with the possibility of lewd images.  You can download it here: https://drive.google.com/file/d/1DvyU0BiRCQ2klhXuJEyR0kh4ikoMnkVb/view?usp=sharing
If you want to censor it like I did in order to avoid making user's uncomfortable, you should be able to just slice off the bottom half of the output.

**Comment by flumf** [comment]
I messed around with truncation, but results weren't *super* great. I wouldn't be surprised if the main issue was the high variation in the data set (along with training on faces + torsos). Thanks for attaching the unfrozen graph btw, I'll take a look at it and see what I can do :)
Chopping off the bottom half is probably what I'm going to end up doing but that's not a huge deal as of right now.
I'm going to close this issue for now as it isn't really an issue, but I might end reopening it if I find anything interesting.
